language_resources = {
    'en_US': {
        'title': 'Version: 1.2',
        'system_info': 'System Info Check',
        'ssh_status': 'SSH Status Detection',
        'gpu_driver': 'GPU Driver Check',
        'large_file': 'Large File Detection',
        'log_collection': 'Log Collection',
        'system_monitoring': 'System Monitoring',
        'file_integrity': 'File Integrity Monitor',
        'config_editor': 'Config Editor',
        'help': 'View Help',
        'about': 'About',
        'help_content': 'Please select an operation according to the prompts on the interface.',
        'about_content': 'Ubuntu 22.04 System issue diagnose tool\nVersion 1.2',
        'System self-check': 'System self-check',
        'Disk space check': 'Disk space check',
        'Operating system information': 'Operating system information',
        'Disk mount': 'Disk mount',
        'Mounting the data disk': 'Mounting the data disk',
        'SSHFS Mount / Unmount': 'SSHFS Mount / Unmount',
        'Mount Share': 'Mount Share',
        'Button 4': 'Button 4',
        'Disk Usage Analyzer': 'Disk Usage Analyzer',
        'Disk space usage': 'Disk space usage',
        'Inode Usage': 'Inode Usage',
        'Repair Options': 'Repair Options',
        'System ssh detection passed': 'System ssh detection passed',
        'repair': 'repair',
        'GPU driver detection': 'GPU driver detection',
        'Checking GPU driver status...': 'Checking GPU driver status...',
        'NVIDIA driver information:': 'NVIDIA driver information:',
        'Large file detection': 'Large file detection',
        'Start detection': 'Start detection',
        'Enter minimum file size (MB) default 1000 MB': 'Enter minimum file size (MB) default 1000 MB',
        'Filter time': 'Filter time',
        'Select time period:': 'Select time period:',
        'Filter by number of rows': 'Filter by number of rows',
        'Enter the number of rows:': 'Enter the number of rows:',
        'Enter the number of rows, for example 100': 'Enter the number of rows, for example 100',
        'Log Collection': 'Log Collection',
        'Deployment monitoring': 'Deployment monitoring',
        'Start monitoring': 'Start monitoring',
        'Checking the deployment status': 'Checking the deployment status',
        'Stop monitoring': 'Stop monitoring',
        'Remove monitoring': 'Remove monitoring',
        'Monitoring status: Unknown': 'Monitoring status: Unknown',
        'Deployment monitoring output...': 'Deployment monitoring output...',
        'Start monitoring output...': 'Start monitoring output...',
        'Checking the deployment status output...': 'Checking the deployment status output...',
        'Stop monitoring output...': 'Stop monitoring output...',
        'Remove monitoring output...': 'Remove monitoring output...',
        'deploying monitoring': 'deploying_monitoring',
        'Disk monitor deployment': 'Disk monitor deployment',
    },
    'zh_CN': {
        'title': '版本：1.2',
        'system_info': '系统信息检测',
        'ssh_status': 'SSH状态检测',
        'gpu_driver': 'GPU驱动检测',
        'large_file': '检测大文件',
        'log_collection': '日志收集',
        'system_monitoring': '系统监控',
        'file_integrity': '文件完整性监控',
        'config_editor': '配置编辑器',
        'help': '查看帮助',
        'about': '关于',
        'help_content': '请根据界面中的提示选择操作。',
        'about_content': 'Ubuntu 22.04 系统问题诊断工具\n版本 1.2',
        'System self-check': '系统自检',
        'Disk space check': '磁盘空间检查',
        'Operating system information': '操作系统信息',
        'Disk mount': '磁盘挂载',
        'Mounting the data disk': '挂载数据盘',
        'SSHFS Mount / Unmount': 'SSHFS 挂载 / 解挂',
        'Mount Share': '挂载共享目录',
        'Button 4': 'Button 4',
        'Disk Usage Analyzer': '磁盘占用分析器',
        'Disk space usage': '磁盘空间使用情况',
        'Inode Usage': 'Inode 使用情况',
        'Repair Options': '修复选项',
        'System ssh detection passed': '系统ssh检测通过',
        'repair': '修复',
        'GPU driver detection': 'GPU 驱动检测',
        'Checking GPU driver status...': '检查驱动状态...',
        'NVIDIA driver information:': 'NVIDIA 驱动信息:',
        'Large file detection': '大文件检测',
        'Start detection': '开始检测',
        'Enter minimum file size (MB) default 1000 MB': '输入最小文件大小 (MB) 默认 1000 MB',
        'Filter time': '过滤时间',
        'Select time period:': '选择时间段：',
        'Filter by number of rows': '行数过滤',
        'Enter the number of rows:': '输入行数：',
        'Enter the number of rows, for example 100': '输入行数，例如100',
        'Log Collection': '日志收集',
        'Deployment monitoring': '部署监控',
        'Start monitoring': '开始监控',
        'Checking the deployment status': '检查部署状态',
        'Stop monitoring': '停止监控',
        'Remove monitoring': '去除监控',
        'Monitoring status: Unknown': '监控状态: 未知',
        'Deployment monitoring output...': '部署监控输出...',
        'Start monitoring output...': '开始监控输出...',
        'Checking the deployment status output...': '检查部署状态输出...',
        'Stop monitoring output...': '停止监控输出...',
        'Remove monitoring output...': '去除监控输出...',
        'deploying monitoring': '部署监控中...',
        'Disk monitor deployment': '硬盘监控部署',
    }
}
